os:
  - linux
  - osx

language: cpp

dist: bionic

compiler:
  - gcc
  - clang

jobs:
  exclude:
  - osx: linux
    compiler: clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-bionic-8.0
      - g++-7
      - gcc-7
      - clang++-8
      - cmake

script:
  - mkdir build
  - cd build
  - cmake .. && make
  - ctest --verbose CTestTestfile.cmake
