os:
  - linux
  - osx

language: cpp

dist: bionic

compiler:
  - gcc
  - clang

jobs:
  exclude:
  - os: linux
    compiler: clang
  - os: osx
    compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-bionic-8.0
      - g++-7
      - gcc-7
      - clang++-8
      - cmake

install:
  - export DDIR="${HOME}/ddir"
  - mkdir -p ${DDIR} && cd ${DDIR}
  - echo ${TRAVIS_OS_NAME}
  - |
    if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      export CMAKE_URL="https://github.com/Kitware/CMake/releases/download/v3.17.0/cmake-3.17.0-Linux-x86_64.tar.gz";
      mkdir cmake;
      travis_retry wget --no-check-certificate -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake;
      export PATH=${DDIR}/cmake/bin:${PATH};
      echo ${PATH};
    fi
  - cmake --version


script:
  - mkdir build
  - cd build
  - cmake .. -DTEST=1 && make
  - ctest --verbose CTestTestfile.cmake
