{% set version = "1.2.1" %}

package:
  name: kmtricks
  version: {{ version }}

source:
  git_url: https://github.com/tlemane/kmtricks

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - cmake

  host:
    - zlib

  run:
    - zlib

about:
  home: https://github.com/tlemane/kmtricks
  license: AGPL-3.0
  dev_url: https://github.com/tlemane/kmtricks/
  doc_url: https://github.com/tlemane/kmtricks/wiki

extra:
  recipe-maintainers:
    - tlemane
