package:
  name: kmtricks
  version: "0.0.2"

source:
  git_url: https://github.com/tlemane/kmtricks

requirements:
  build:
    - {{ compiler('cxx') }}
    - zlib
    - make
    - cmake
  run:
    - zlib
    - python>=3.6
