package:
  name: kmtricks
  version: "0.0.5"

source:
  git_url: https://github.com/tlemane/kmtricks

requirements:
  build:
    - {{ compiler('cxx') }}
    - zlib
    - make
    - cmake
    - openmp
    - lz4

  run:
    - zlib
    - python>=3.6
    - lz4
    - openmp